replicaCount: 1

image:
  repository: cerit.io/commonprovenanceframework/nro-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8020
  targetPort: 8020
  annotations: {}

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

springProfilesActive: ""

config:
  TP_ID: TrustedParty
  TP_FQDN: cpf-trusted-party:8020
  TP_DB_URL: jdbc:postgresql://nro-postgres:5432/trustedServicedb
  TP_DB_USER: postgres
  TP_TRUSTED_CERTS_DIR: /certs/trusted_certs
  TP_PUBLIC_CERT_PATH: /certs/cert-dev/tp.pem
  TP_PRIVATE_KEY_PATH: /certs/cert-dev/tp.key

existingSecret:
  name: ""
  keys:
    TP_DB_PASSWORD: tp-db-password

extraEnv: []

certs:
  existingSecret:
    name: ""
    mountPath: /certs
    items:
      tp.pem: cert-dev/tp.pem
      tp.key: cert-dev/tp.key
      ca.pem: trusted_certs/ca.pem

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 6
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 6
startupProbe: {}
